version: '3'

services:
  php:
    container_name: mega-sena-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mega-sena-network

  nginx:
    container_name: mega-sena-nginx
    build:
        context: ./docker/nginx
        dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
        - '8080:80'
        - '443:443'
    volumes:
        - ./:/var/www
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
        - mega-sena-network

  mysql:
    container_name: mega-sena-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - mega-sena-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - mega-sena-network
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}


  phpmyadmin:
    container_name: mega-sena-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    networks:
      - mega-sena-network
    environment:
      PMA_HOST: mega-sena-mysql
    depends_on:
      - mysql
  redis:
    container_name: mega-sena-redis
    build:
        context: ./docker/redis
        dockerfile: Dockerfile
    ports:
    - '6379:6379'


networks:
  mega-sena-network:
    driver: bridge


volumes:
  mega-sena-data:
    driver: local
